recipe: default.v1
language: en
pipeline:
- name: llm_intent_classification.llmIntentClassifier


policies:
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.5
  core_fallback_action_name: action_default_fallback
  enable_fallback_prediction: true
assistant_id: 20230410-232747-chestnut-porter
