recipe: default.v1
language: en
pipeline:
- name: SpacyNLP
  model: en_core_web_md
  case_sensitive: false
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 300
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 300
  constrain_similarities: true
- name: FallbackClassifier
  threshold: 0.1
  ambiguity_threshold: 0.1
policies:
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.01
  core_fallback_action_name: action_default_fallback
  enable_fallback_prediction: true
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 300
- name: TEDPolicy
  max_history: 5
  epochs: 300
  constrain_similarities: true
assistant_id: 20230410-232747-chestnut-porter
